author:  "" 
description:  "" 
url:   "" 
email:  "" 
title:  "" 

theme: minima



header_pages:
  - _pages/homepage.md
 

include:
    - _pages
    
    
 


plugins:
 - jekyll-feed
 - jekyll-seo-tag
